Update codeowners
ethereum/esp-website pull request #380
Opened 2024-06-21 19:43 UTC by pettinarip

## Description

Removing samjammin and adding @minimalsm.

2024-06-21 20:18 UTC, wackerow approved these changes

2024-06-21 21:30 UTC, wackerow requested changes
The `*` here is a wildcard for all paths

2024-06-21 21:30 UTC, wackerow commented on .github/CODEOWNERS
> +- @minimalsm @wackerow @corwintines @pettinarip @nhsz
```suggestion
* @minimalsm @wackerow @corwintines @pettinarip @nhsz
```

2024-06-22 07:47 UTC, pettinarip commented on .github/CODEOWNERS
> +- @minimalsm @wackerow @corwintines @pettinarip @nhsz
Ah thanks, good catch

2024-06-24 12:23 UTC, nhsz approved these changes

2024-07-04 04:45 UTC, corwintines approved these changes

2024-07-04 04:45 UTC, merged